### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by manugarri** [Dataherald/dataherald#120]
Awesome project! I am testing some queries, and after setting up a connection, scanned a table and add one golden record, running a query sometimes returns a 404 with the following output:
 ```
Error: Not FoundResponse bodyDownload{   "detail": "Got unexpected type of `handle_parsing_errors`" }
--
```

Is there a way to get a better error message?

**Comment by jcjc712** [comment]
Sure, We are working on improving the error messages

**Comment by DishenWang2023** [comment]
This error has been handled by @jcjc712 in https://github.com/Dataherald/dataherald/pull/122, I'll be closing this issue.
