### ISSUE TITLE
class `SQLDatabase` in `dataherald/sql_database/base.py` does not have a constructor!

### ISSUE THREAD

**Issue by massivefermion** [Dataherald/dataherald#127]
I've been trying to work with this but when I use the `/api/v1/scanner` endpoint, I get the error:

> "Unable to connect to db: <db>"

After doing some detective work, it turns out that the problem comes from the fact that when `from_uri` tries to create an instance of `SQLDatabase`, an exception is raised because `SQLDatabase` does not have a constructor.

I added a constructor and called super, but I still get the "Unable to connect..." error. (of course the error is different if you don't call super, that's how I know the initial problem was the lack of a constructor!)

Thanks

P.S.
Forgot to mention! Before calling the `scanner` endpoint, I did of course use the `/api/v1/database` endpoint to introduce my database and did get the `true` response.

**Comment by aazo11** [comment]
Hi @massivefermion -- thanks for highlighting this. I do not think the issue you are hitting is related to the constructor, rather for some reason the engine (and SQLAlchemy) is having trouble connecting to your DB. To help debug could you provide the following:

- What type of database or warehouse are you connecting to?
- Are you using SSH for the DB connection?
- Can you send me the requestBody sent to `/api/v1/database` or the object from Mongo (with sensitive info removed)?

You can find more documentation (including sample URI connections [here](file:///Users/aazo11/Documents/GitHub/dataherald/docs/_build/html/api.database.html)

Thanks

**Comment by rmaroun** [comment]
I have she same issue and fixed it, @aazo11 I can submit a PR for it today?

**Comment by massivefermion** [comment]
> Hi @massivefermion -- thanks for highlighting this. I do not think the issue you are hitting is related to the constructor, rather for some reason the engine (and SQLAlchemy) is having trouble connecting to your DB. To help debug could you provide the following:
> 
>     * What type of database or warehouse are you connecting to?
> 
>     * Are you using SSH for the DB connection?
> 
>     * Can you send me the requestBody sent to `/api/v1/database` or the object from Mongo (with sensitive info removed)?
> 
> 
> You can find more documentation (including sample URI connections here
> 
> Thanks

I just copied the `curl` requests from the readme and changed the host and the body.
This is what I sent(copied exactly from the terminal, `172.20..0.3` is the app container ip address):
```
 curl -X 'POST' \
  '172.20.0.3/api/v1/database' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "db_alias": "herald",
  "use_ssh": false,
  "connection_uri": "postgresql://postgres:1234@localhost/herald"
```
which returned true!
Then I sent:
```
curl -X 'POST' \
  '172.20.0.3/api/v1/scanner' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "db_alias": "herald",
    "table_name": "users"
  }'
```
which returned:
> {"detail":"Unable to connect to db: herald"}

And this is what I have in mongo at this moment:
```
[
  {
    _id: ObjectId("64ec4ca4fda39c365fb94403"),
    alias: 'herald',
    use_ssh: false,
    uri: 'gAAAAABk7EykFLWC-6aKkjztrC7eq7Wk2vFWBLYy3vyuAgNFP3S91y02kuvlyLRa2J8VoRih4uYuePSTmj6JnaidfV903X-kGEXOmNAlUdlifAwX1T6bDFp2yyxqdHq5qZBf0ylmp7PD',
    ssh_settings: null
  }
]
```

**Comment by rmaroun** [comment]
@massivefermion submitted a PR (issue was due to encoded connection_uri after being decoded with fernet. [https://github.com/Dataherald/dataherald/pull/129](PR-129)

**Comment by massivefermion** [comment]
@rmaroun I tried what you did, but it didn't solve the issue!

**Comment by rmaroun** [comment]
@massivefermion then it might be your connection string, are you using docker on a macbook? Is the postgres database on your host and not within your docker environment?

**Comment by massivefermion** [comment]
Thanks @rmaroun 
It was entirely my fault. The postgres instance was not in the same docker network as dataherald.

**Comment by rmaroun** [comment]
@massivefermion is it working now? with the fix I shared or also without it? what is your final connection string so we can share it with the rest of the community. thanks
