### ISSUE TITLE
How to get `table_description_id` to add columns descriptions?

### ISSUE THREAD

**Issue by mrtunguyen** [Dataherald/dataherald#184]
Hello, 

Nice project! I played around with this but wonder that how we can get `table_description_id ` to add to this endpoint `PATCH /api/v1/table-descriptions/{table_description_id}`? I see nowhere in the code that add `table_description_id` in `table_descriptions` collection. 

Thanks.

**Comment by jcjc712** [comment]
Hi, thanks.
To get table_description_id please follow the next steps.
1. You should create a db connection using this endpoint POST `/api/v1/database-connections` 
Here your can find the documentation for this endpoint https://dataherald.readthedocs.io/en/latest/api.create_database_connection.html

2. If you are working with the latest version that was deployed yesterday use this endpoint to scan your db connection tables. POST `/api/v1/table-descriptions/sync-schemas` if you have the old version, the endpoint is this one POST `/api/v1/table-descriptions/scan`
Here your can find the documentation for this endpoint https://dataherald.readthedocs.io/en/latest/api.scan_table_description.html

3. Once the scanning finishes you can use this endpoint to get the list of table-descriptions GET `/api/v1/table-descriptions`
Then you should get a list of your scanned tables and the `id` is the `table_description_id ` for this endpoint PATCH `/api/v1/table-descriptions/{table_description_id}`
Here your can find the documentation for this endpoint https://dataherald.readthedocs.io/en/latest/api.list_table_description.html

Please let me know if your have more questions.

**Comment by mrtunguyen** [comment]
hmm it seems ok now. I did the same thing yesterday but when running `GET /api/v1/table-descriptions`, it returns empty. thanks for your response.
