### ISSUE TITLE
chroma vector store doesn't return similar questions (even the same question)

### ISSUE THREAD

**Issue by mrtunguyen** [Dataherald/dataherald#187]
Hi, 

I encountered the problem that the chroma vector store doesn't return exact the same question that was put into the golden records. When I deep dive into the code, I found out that when you add record into chroma collection, you don't add embeddings for that record, which become `None`. I think that's why it doesn't work as expected. 

https://github.com/Dataherald/dataherald/blob/9e39613b21edcd3beb893a3144511dffc8bc5185/dataherald/vector_store/chroma.py#L44

**Comment by mrtunguyen** [comment]
Hmm I think my bad when concluding too quickly that it returns `None` as embedding. refer to this [issue](https://github.com/chroma-core/chroma/issues/300). 
In fact, the chroma collection uses `ONNXMiniLM_L6_V2` as default embedding function. so it should be fine. 

But why when I query exactly the same question which exists in `target_collection`, it doesn't return anything?

**Comment by MohammadrezaPourreza** [comment]
Hello @mrtunguyen,

I want to express my gratitude for your valuable contribution to enhancing our work.

I've conducted tests on the latest version of Dataherald, and using ChromaDB, I was able to successfully retrieve the same question that I had added as golden records.

One potential reason for not obtaining results from the Chroma vector store could be related to the way ChromaDB stores vectors in memory. Whenever you create a new container with the --build flag, you lose the previously stored vectors in ChromaDB. However, please be aware that you will still see the golden records stored in the Mongo collection.
Thank you once again for your efforts and contributions.

**Comment by jcjc712** [comment]
@mrtunguyen 
**We have identified two potential solutions:**

**1. Script-Based Solution:** 
One approach involves creating a script that runs each time the app container starts up. This script would be responsible for retrieving all the 'golden_records' rows and seamlessly inserting them into Chroma.

**2. Dockerized Chroma Solution:** 
Alternatively, you can opt to create a Chroma container within the 'docker-compose' file and configure the necessary volumes to persist the data. Then, in our current Chroma implementation located in the 'vector_store' folder, establish a connection to the newly created Chroma container.

If you do implement these it would be great if you could raise a (PR). Otherwise we will get a fix in place early next week.

**Comment by ppmarkus** [comment]
I have build a script-based solution that takes config from json files and other database stores.

Data that doesn't change much like database-connections and table-descriptions, instructions can be stored as json in a file and loaded but golden-records are updated over time to provide better coverage.

I run the script on demand when some config data changes. 
The script just deletes all entries like golden-records by first retrieving them all from the DB and then calling the the delete API. After that it calls the API to create new ones. That way I know that both Mongo DB and the Chroma memory is updated (at least in the case of DefaultContextStore)

I'm wondering if this is something I can contribute with?
I could make assumptions about the format (json) and standardize the the attributes and then provide a script to refresh the context when the script is run (which could be on container load too)

**Comment by ppmarkus** [comment]
In my case it is just the default Chroma Context Store but I think it doesn't matter because the scripts use the API to upload. As long as your flavor of Context Store implements the dataherald.context_store.ContextStore the interface is supported.

**Comment by jcjc712** [comment]
@mrtunguyen Hi, We added a script to upload the golden records in vector stores (Chroma|Pinecone) from MongoDB golden_records collection. Please check this in the [documentation](https://dataherald.readthedocs.io/en/latest/tutorial.run_scripts.html#script-to-populate-golden-records)

Just run this command:
```
docker-compose exec app python3 -m dataherald.scripts.delete_and_populate_golden_records
```
