### ISSUE TITLE
Add support for multiple schemas

### ISSUE THREAD

**Issue by roy-moven** [Dataherald/dataherald#217]
Currently DataHerald only seems to know or care about the default schema. I tried to provide some convenient reporting views in another schema, but DataHerald ignores them. (PostgreSQL)

**Comment by ppmarkus** [comment]
I asked about this on the discord and the reply was that DH is focusing on single database/schema for the time being as this is a common use case. From the code you can see that everything is tied to a db_connection_id which requires the specify the database/schema in the connection string. I found myself just moving over a few tables to a central schema (We're using MariaDB but concept is similar to PostgreSQL I think). Of course it depends on the use case and you might not be able to transfer tables/views. DH is still in early days so this is something that could be added in the future. I was looking into it but I think then opted for the easier route for now.

I'd be interested to discuss how it might make sense to be achieved. 
I think the current setup makes it easy to organize and makes things not so complicated at least.
However,  if say, golden-records could be specified with tables from any schema and then the context was built with table and other info from any schema then it could possibly work.

**Comment by roy-moven** [comment]
I think it would have to look like - everywhere we accept a `table_name` we also accept an optional `schema_name`. If `schema_name` is not specified then `table_name` is assumed to be in the default (public) schema, just like in SQL.

**Comment by aazo11** [comment]
HI @roy-moven -- you can connect to schemas other than the default schema by specifying the schema in the connection_uri like below

`connection_uri": postgresql+psycopg2://<user>:<password>@<host>:<port>/<db-name>?options=-csearch_path=<my-schema>`

You can read more about this in our documentation [here](https://dataherald.readthedocs.io/en/latest/api.create_database_connection.html)

We currently do not support question answering from multiple databases concurrently, however this is a feature we are adding before year end.

**Comment by roy-moven** [comment]
Thank you @aazo11 that's a useful workaround! I missed that in the documentation.
