### ISSUE TITLE
After redeploying DH, fewshot_examples_retriever doesn't work

### ISSUE THREAD

**Issue by ppmarkus** [Dataherald/dataherald#222]
Recently I started to experience this scenario after redeploying DH (both DH/mongo containers).

```
> Entering new AgentExecutor chain...
Action: fewshot_examples_retriever
Action Input: << input question >>
Observation: fewshot_examples_retriever is not a valid tool, try one of [sql_db_query, get_admin_instructions, get_current_datetime, db_tables_with_relevance_scores, db_relevant_tables_schema, db_relevant_columns_info, db_column_entity_checker].
```

But if after re-deploy, I refresh all the golden-records (i.e. delete/upload via API), it works again.
I'm using the default VECTOR_STORE and CONTEXT_STORE.

This didn't happen before.
Can't figure out why this is happening yet.

**Comment by MohammadrezaPourreza** [comment]
@ppmarkus Hi Markus, I'm looking into this issue, and let you know as soon as we find the bug or solution. Thanks for all your contribution so far.

**Comment by MohammadrezaPourreza** [comment]
@ppmarkus This PR: https://github.com/Dataherald/dataherald/pull/224 should address the issue you mentioned. 
Please let me know if the issue still persists. Thanks.

**Comment by ppmarkus** [comment]
Hi @MohammadrezaPourreza,
Np thank you vm for looking into it.
Today OpenAI API was down for most of the day for us which I didn't experience before.
I'm sure it'll improve over time but shows that having multiple vendors is a good idea.

After testing the change, I see that the previous observation namely this one below is gone

```
Observation: fewshot_examples_retriever is not a valid tool, try one of [sql_db_query, get_admin_instructions, get_current_datetime, db_tables_with_relevance_scores, db_relevant_tables_schema, db_relevant_columns_info, db_column_entity_checker].
```

but DH goes straight into Action: db_tables_with_relevance_scores

```
> Entering new AgentExecutor chain...
Action: db_tables_with_relevance_scores
Action Input: << Question >>
Observation: Table: <<table>>, relevance score: 0.711, ...
```

If I rerun the POST [/api/v1/golden-records] API end point then it works as expected.

```
> Entering new AgentExecutor chain...
Action: fewshot_examples_retriever
Action Input: 5
Observation: Question: ....
```

**Comment by MohammadrezaPourreza** [comment]
@ppmarkus Thank you for your insightful comment. I'm a bit unclear on the issue at hand. Currently, the engine's workflow involves calling the fewshot_examples_retriever tool when there are golden records present. However, in cases where there are no golden records, the agent skips the fewshot_examples_retriever tool and proceeds directly to the next tool, which is db_tables_with_relevance_scores.

**Comment by ppmarkus** [comment]
Hi @MohammadrezaPourreza 
Np. That makes sense of course. If there are no golden-records then the agent will carry on and use the next best option (db_tables_with_relevance_scores)

What I meant was that say I initialize the server (db/tables/golden records) via the API and it works as expected (fewshot_examples_retriever agent is used), but then if I then bounce DH (stop/start via docker compose), the golden records are then not referenced when asking a question. I can see the entries in MongoDB but perhaps but as mentioned above are used. (DataheraldSQLAgent.create_sql_agent() is being called with max_examples=0)

Just to confirm, is it expected behaviour that the golden-records need to be re-applied via the API after bouncing DH?

**Comment by MohammadrezaPourreza** [comment]
@ppmarkus Thank you for providing clarification.

Re-applying these settings after bouncing DH is not an expected behavior. Could you kindly inform me which vector store you are using: Chromadb or Pinecone?
If you are using Chromadb, this behavior is expected since the golden records in the vector store are stored within containers, and they are lost when the container is rebuilt.
Regarding the 'max_examples' setting, I couldn't locate the specific reference you mentioned. The default value for golden records was intended to be set at five (max_number_of_examples: int = 5  # maximum number of question/SQL pairs).

**Comment by ppmarkus** [comment]
Hi @Mo, thank you for the clarification. 
I am using the default Chromadb so it all makes sense now. I see the chromadb persistent store being initialized.
I have added a step in our ci/cd pipeline to re-apply the golden-records after DH is deployed.
Thank you for your patience and explanation.
