### ISSUE TITLE
Support for duckdb

### ISSUE THREAD

**Issue by jineshshah36** [Dataherald/dataherald#231]
I’d love to know if you plan to support duckdb and/or if you can point me in the right direction to add support.

**Comment by aazo11** [comment]
Hi Jinesh -- funny you brought this up because we are starting this from this week. Would love to collaborate if you are using DuckDB in your project right now.

**Comment by MohammadrezaPourreza** [comment]
@jineshshah36 Hi, we merged the code to support DuckDB integration. You have to use MotherDuck to host your db then connect it to our engine. We also included a how to in readme.
let us know if you need more information.
