### ISSUE TITLE
Can u support Azure Open AI APIs?

### ISSUE THREAD

**Issue by vikrant-sahu** [Dataherald/dataherald#232]
The SDKs for Azure OPEN AI n OPEN AI are different.
Azure requires a few more credentials. Can you please support this?

Meanwhile please let me know where all changes needed to support Azure APIs. Will make the changes and file a PR.

**Comment by MohammadrezaPourreza** [comment]
Hi @vikrant-sahu , supporting different LLMs and LLM providers, other than OpenAI is on our roadmap. 
We would really appreciate it if you make the changes to support Azure Open AI. 
The files that you need to change:
All of the agents and evaluators create the LLM object when they are called by using the get_model() function that is defined inside the model/chat_model.py. You have to change that file to add the support for Azure OPEN AI.
We are also using openAI embeddings, so you might want to change that as well. which is used inside pinecone.py and dataherald_sqlagent.py files.

**Comment by MohammadrezaPourreza** [comment]
@vikrant-sahu Azure OpenAI is now supported seamlessly without the need for any code changes. You can simply set the 'api_base' in both the 'sql_generation' and 'nl_generation' endpoints.
