### ISSUE TITLE
Query containing markdown (```sql) causing sql_db_query action to fail and try again in a loop

### ISSUE THREAD

**Issue by ppmarkus** [Dataherald/dataherald#240]
I experienced the following issue after generating the sql query (Action: sql_db_query) I'd get the following error:

Model used: gpt-4-1106-preview
(note when I tried using gpt-4 instead it couldn't even create the sql properly in this case)

**DH Log output**
Observation: Error: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\```sql\n-- This query retrieves xxxxxx...' at line 1")
[SQL: ```sql

...

Thought:The error occurred because the SQL query was submitted **with markdown code block syntax (\```sql)** which is not part of the actual SQL query. I need to remove the markdown syntax and resubmit the query.

It seems like it's coming from the QuerySQLDataBaseTool

---
And then this would loop many times until the **RateLimitError** was produced.
We ran out of run quota (gpt-4-1106-preview can only be run 100 times a day). I'll try to get more information tomorrow.

**DH Log output**
Action: sql_db_query
Action Input:

...

Observation: Error: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\```sql\n-- This query retrieves xxxxxxx...' at line 1")
[SQL: ```sql

Thought:The error occurred again because the SQL query was submitted with markdown code block syntax (```sql) which is not part of the actual SQL query. I need to remove the markdown syntax and resubmit the query without the markdown code block syntax.

Observation: Error: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '``sql\n-- This query retrieves daily crowding data for instrument 7203 for th...' at line 1")

Thought:The error occurred again because the SQL query was submitted with markdown code block syntax (```sql) which is not part of the actual SQL query. I need to remove the markdown syntax and resubmit the query without the markdown code block syntax.

Action: sql_db_query
Action Input:

etc., etc.,

**Comment by aazo11** [comment]
We will look into this and keep you posted @ppmarkus

**Comment by MohammadrezaPourreza** [comment]
@ppmarkus Hi, I'm so sorry to hear that you have this issue with our engine. Based on the logs I assume the issue is with the comments that are generated by the agent, please try removing this line "`The SQL query MUST have in-line comments to explain what each clause does."` from utils.agent_prompts.py.

**Comment by ppmarkus** [comment]
Hi @Mo, no problem. Thank you for the reply. Ah I see. I was thinking that it was perhaps due to the the ```sql but what you say makes sense. 
the query it produced which appeared in the log is correct though. Maybe I can modify the line to say  `The SQL query MUST have in-line comments to explain what each clause does EXCEPT don't add a comment before the query` (something like this)

I will try playing around with some options tomorrow when I can use the same model again (daily quota reset)

**Comment by MohammadrezaPourreza** [comment]
@ppmarkus In our internal benchmarking on Spider, we observe a similar issue with the gpt-3.5-turbo-1106, I think with their new update, models are generating this ```sql. Also try to explicitly mention in the prompt to not use ```sql in the generated SQL query.

**Comment by ppmarkus** [comment]
Hmmm. so it looks like the issue just went away.
first I modified the Agent Prompt to `The SQL query MUST have in-line comments to explain what each clause does EXCEPT don't add a comment before the query`. I got no comments in the output sql and no validation error either. 
So I assume then it was the sql starting with the comment "--" was causing the issue previously.

but then I also tried `The SQL query MUST have in-line comments to explain what each clause does HOWEVER the query shouldn't start with a comment.`  and got the same result (no comments and no error).

After that I reverted back to the original  `The SQL query MUST have in-line comments to explain what each clause does.` and still no comments and no errors.

I didn't change anything else that I'm aware of and the plan, llm_chain should be the same. The temperature of the llm settings is set to 0. I see the same actions being executed. Maybe the model was updated internally? 

I'll see if it happens again. For now no need to further investigate.

Thank you for the help and feedback.

**Comment by ppmarkus** [comment]
Note that the issue returned again.

But it looks like it really was the mark down (\```sql \```) causing the issue. 

It was clear with this message.

```
Thought:The SQL query syntax error occurred because the input to the sql_db_query tool included markdown code block syntax (```sql and ```), which is not part of the SQL language. I need to remove the markdown syntax and resubmit the query.
```

I tried with several other formats and also tried adding to the tips e.g. ```tip6) Remove any markdown formatting from the SQL query before executing it. For example tripple backticks (```) and ```sql```


What worked finally was when I modified the _run() method in the QuerySQLDataBaseTool

```python
    @catch_exceptions()
    def _run(
        self,
        query: str,
        top_k: int = TOP_K,
        run_manager: CallbackManagerForToolRun | None = None,  # noqa: ARG002
    ) -> str:
        # remove markdown formatting from the query if it exists. ```sql from the start and ``` from the end
        if "```" in query:
            logger.info(f"**** Removing markdown formatting from the query\n")
            query = query.replace("```sql", "").replace("```", "")
            logger.info(
                f"**** Query after removing markdown formatting: {query}\n")
        """Execute the query, return the results or an error message."""
        return self.db.run_sql(query, top_k=top_k)[0]
```

Do you think this is something that would make sense to merge into main?
It could be that this issue should be fixed further up the call chain.

**Comment by MohammadrezaPourreza** [comment]
@ppmarkus Thank you so much. We have detected the same thing even with gpt-3.5-turbo-1106, it is primarily due to the OpenAI update and if you take a look at here : https://platform.openai.com/examples/default-sql-translate , they added those markdown for SQL queries. Your fix will help the agent to construct the SQL queries, but we need to also remove the markdowns before creating the response, since the evaluators also run the SQL queries and we have to remove the markdowns from the intermediate steps. Could you please raise your PR so I can make other changes on your branch? Thank you so much for all your help, we really appreciate it.

**Comment by ppmarkus** [comment]
Hi @MohammadrezaPourreza.  Apologies for the slow response and thank you for the quick fix already. 
Yes I had also saw the same problem with the evaluators/intermediate steps and added similar logic locally etc., to bypass. Np. I'll update my repo with the fixes.
I guess it makes sense for the LLM if you want to pretty display the output sql in a browser.
Thanks vm!
