### ISSUE TITLE
Ms SQL Support

### ISSUE THREAD

**Issue by Namec999** [Dataherald/dataherald#258]
Hello All,
does anyone achieved a connection to an MS SQL server instance.

if yes can you show how to do this.

**Comment by ppmarkus** [comment]
For this I believe you'll need to install something like pymssql and then provide an appropriate connection string.

See this link for sqlalchemy MSSql API support
https://docs.sqlalchemy.org/en/20/dialects/mssql.html

I use MariaDB and include PyMySql in the deployment process and it all works without issue.

**Comment by ppmarkus** [comment]
Actually, that's a good point. I should just merge my change so that DH will be compatible with **MariaDB/MySQL**
Simple addition to the requirements.txt

**Comment by jcjc712** [comment]
@ppmarkus @Namec999 Hi, we are still updating the documentation but it supports **MariaDB/MySQL** connection. 
The URI structure would be like this:
`mysql+pymysql://username:password@hostname:port/database_name`
