### ISSUE TITLE
PRIMARY KEY definition on the table descriptions

### ISSUE THREAD

**Issue by mmahmed** [Dataherald/dataherald#351]
https://github.com/Dataherald/dataherald/blob/7016ac9673226faf5279aa88df924ae732b3b6f8/dataherald/db_scanner/sqlalchemy.py#L145

This seems to have messed up the PRIMARY KEY definition in the create_table_ddl as Column is newly initialised with only col.name, col.type ignoring all other properties present on valid_columns Column list.

Also foreign key should be included in the ddl.

**Comment by MohammadrezaPourreza** [comment]
@mmahmed Thank you for raising this point. We have incorporated foreign key and primary constraints into each column object model, and our engine utilizes them accordingly.
