### ISSUE TITLE
Is there an open-source community driven frontend for dataherald ? 

### ISSUE THREAD

**Issue by Antonhansel** [Dataherald/dataherald#359]
Hello,

I've been working on a frontend for dataherald and I was wondering if there is an open source frontend around ? If not, I'll consider rebuilding mine from scratch and make it available to the community.

Thank you for this amazing tool,

**Comment by MohammadrezaPourreza** [comment]
@Antonhansel Hello, at the moment, we do not have an open-source frontend available for our open-source engine. We would greatly appreciate it if you could share your valuable work with us. Thank you!
