### ISSUE TITLE
invalid literal for int() with base 10: '

### ISSUE THREAD

**Issue by nalz** [Dataherald/dataherald#392]
I hooked up the library to a test table in BQ. Then synced it using the sync-schemas endpoint. I was able to verify that the connection was established correctly and logs were returned as well. Now without adding any context, i sent a request to generate sql - "Give me all records from X table" and ran into this error.

**Comment by jcjc712** [comment]
Hi, thanks for you comment. We will try to identify the issue but it would be helpful if you share the logs to see where it is failing. Thanks

**Comment by jcjc712** [comment]
Hi, can you check that in your env file this var is not empty `DH_ENGINE_TIMEOUT`?  if so it sets a space as the value so when this `int(os.getenv('DH_ENGINE_TIMEOUT'), 150)` is executed it raises the error. To fix it you can set a number in your .env file for example:
`DH_ENGINE_TIMEOUT = 150` or delete it and it would take the default value. Once you fix the .env file don't forget to rebuild your docker container so it can take the envvar changes
`docker-compose up --build`

Please, let me know if it worked

**Comment by pmchugh3** [comment]
I got this error myself, the confusion is that the docs do not tell you that you have to specify DH_ENGINE_TIMEOUT and UPPER_LIMIT_QUERY_RETURN_ROWS, and the comment implies that they default, but if you do not specify them you get this error. I think there is either a bug fix needed to set blank values to default or the example env file needs to be updated to include the values explicitly.

**Comment by pmchugh3** [comment]
Actually there are more potential solutions, the docs being updated to say they need to be filled in would also be sufficient.

**Comment by jcjc712** [comment]
Thanks for your feedback, we will work to improve the documentation and fix that it fails when the env var is not set
