### ISSUE TITLE
How to provide table documentation to the model?

### ISSUE THREAD

**Issue by moltar** [Dataherald/dataherald#395]
Let's say we have extensive docs of every column available to us.

What is the best way to provide this context to the model?

Will it introspect the database and discover these comments?

What about engines that do not support comments?

**Comment by jcjc712** [comment]
Hi, You can use the UPDATE table description endpoint `PUT /api/v1/table-descriptions/{table_description_id}` and set the descriptions per columns and tables. The Agents uses the `descriptions` field to provide more context.

If you mean the create table command when it scans the tables it gets this and is stored in the `table_schema` field and used by the agents.

**Comment by moltar** [comment]
Ah, great, thanks!! Didn't realize there was an API for this.
