### ISSUE TITLE
Create database and tables through the API

### ISSUE THREAD

**Issue by moltar** [Dataherald/dataherald#396]
I have a use case where I have known table structure, data types, descriptions, but no actual database to connect to. It's for an obscure AWS product that uses Athena under the hood. So the database queries would be Athena-like. It's just there is no real connection to specify that could be used to read the schema from.

I could, as a workaround, create a fake Glue catalog of the same shape, and then provide it to Dataherald.

But given the insight in #395 (API endpoints to update descriptions), I was wondering if there's a use case for being able to create the entire database and all of the tables via the API alone, without having to connect to a database?

I could then use the known table models and feed them to DH directly, without having to create fake Athena database.

Thanks.

**Comment by jcjc712** [comment]
Hi, thanks for asking. Currently we can only create `table-descriptions` resources through the `POST /api/v1/table-descriptions/sync-schemas` endpoint and it only works with an existing db connection. So the best option is to create a fake db with the same structure then create the db connection and sync the schemas using the endpoints to create the table descriptions.

If you don't have data to populate the fake db, you can update the table descriptions after they are created to provide more information.
Regards,

**Comment by moltar** [comment]
@jcjc712 Is it really completed or did you close because there aren't plans for this?
