### ISSUE TITLE
422 error while creating database connection with MySQL 5.7

### ISSUE THREAD

**Issue by rajeshmohapatra-ayla** [Dataherald/dataherald#407]
Hello,

I am testing this on my local machine with MySQL 5.7. Does it support mysql 5.7 or any specific version?

The following call fails with 422 for me. Can't make out what is the error here. Appreciate any clue.

```
bash-3.2$ curl -X POST 'http://localhost/api/v1/database-connections' --header 'Content-Type: application/json' --data-raw '{ "alias": "test", "use_ssh": false, "connection_uri": mysql+pymysql://<user>:<passwd>@localhost:3306/openai }'

{"detail":[{"loc":["body",55],"msg":"Expecting value: line 1 column 56 (char 55)","type":"value_error.jsondecode","ctx":{"msg":"Expecting value","doc":"{ \"alias\": \"test\", \"use_ssh\": false, \"connection_uri\": mysql+pymysql://<user>:<passwd>@localhost:3306/openai }","pos":55,"lineno":1,"colno":56}}]}

bash-3.2$
```

**Comment by habibur4340** [comment]
@rajeshmohapatra-ayla 
Testing locally with MySQL 5.7 and encountered a 422 error during a POST request. The error suggests a JSON parsing issue at a specific position in the payload. Here's the command used:

`curl -X POST 'http://localhost/api/v1/database-connections' --header 'Content-Type: application/json' --data-raw '{ "alias": "test", "use_ssh": false, "connection_uri": "mysql+pymysql://<user>:<passwd>@localhost:3306/openai" }'
`
Error Received:
`{"detail":[{"loc":["body",55],"msg":"Expecting value: line 1 column 56 (char 55)","type":"value_error.jsondecode", ...}]}
`
Recommendation: For API testing and troubleshooting, [Apidog](https://apidog.com/) might be beneficial. It provides comprehensive tools for API monitoring and testing, which could help in identifying and solving issues like this more efficiently.

**Comment by rajeshmohapatra-ayla** [comment]
@jcjc712 thank you for response. But I tried that as well. But no luck. Also, not sure why it complains about llm_api_key as well. I have that configured in .env file already.

{
    "detail": "2 validation errors for DatabaseConnection\nconnection_uri\n  Fernet key must be 32 url-safe base64-encoded bytes. (type=value_error)\nllm_api_key\n  Fernet key must be 32 url-safe base64-encoded bytes. (type=value_error)"
}

May be I should try with another database like PSQL and see how it goes.

```
curl --location 'http://localhost/api/v1/database-connections' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
    "alias": "mysqlai2",
    "use_ssh": false,
    "connection_uri": "mysql+pymysql://<user>:<password>@localhost:3306/openai"
}'
```

**Comment by rajeshmohapatra-ayla** [comment]
Tried with PostgreSQL. Same error.

{
    "detail": "2 validation errors for DatabaseConnection\nconnection_uri\n  Fernet key must be 32 url-safe base64-encoded bytes. (type=value_error)\nllm_api_key\n  Fernet key must be 32 url-safe base64-encoded bytes. (type=value_error)"
}

```
curl --location 'http://localhost/api/v1/database-connections' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
    "alias": "psqlai",
    "use_ssh": false,
    "connection_uri": "postgresql+psycopg2://postgresql:<passwd>@localhost:5432/openai"
}'

```
```

bash-3.2$ docker ps
CONTAINER ID   IMAGE            COMMAND                  CREATED          STATUS          PORTS                               NAMES
f45d2a92113d   postgres         "docker-entrypoint.s…"   20 minutes ago   Up 20 minutes   0.0.0.0:5432->5432/tcp              postgres-container
37aed3da2247   dataherald_app   "uvicorn dataherald.…"   13 hours ago     Up 13 hours     0.0.0.0:80->80/tcp                  dataherald_app_1
01691d9ba1d8   mongo:latest     "docker-entrypoint.s…"   3 days ago       Up 13 hours     0.0.0.0:27017->27017/tcp            dataherald_mongodb_1
f2a7ef3fa154   mysql:5.7        "docker-entrypoint.s…"   3 weeks ago      Up 13 hours     0.0.0.0:3306->3306/tcp, 33060/tcp   mysqlserver4
bash-3.2$
```

**Comment by rajeshmohapatra-ayla** [comment]
Sent too fast.
Actually, that error is resolved after I corrected the ENCRYPT_KEY to use the right key from the Fernkey (MBQgsTU8XtwI0uulBdwv4rSyipLTNoaCeejb5Hpumn8=)

**Comment by rajeshmohapatra-ayla** [comment]
Thank you for your help and support.
