### ISSUE TITLE
How to specify the tables to be used when generating a query?

### ISSUE THREAD

**Issue by zhanpengjie** [Dataherald/dataherald#446]
I have many tables in my database, and I would like to be able to specify the tables that can be used in a query, while also improving query accuracy

**Comment by Harshitdy** [comment]
Hello @zhanpengjie, As far I know you can sync you tables using `api/v1/table-descriptions/sync-schemas` endpoint and you can specify your tables like 
```
{
  "db_connection_id": "660aab39fd8c1351d3b4b2c4",
  "table_names": [
    "table1", "table2",......
  ],
  "metadata": {}
}
```
