### ISSUE TITLE
Error while using Create SQL generation API 

### ISSUE THREAD

**Issue by akshayrakate** [Dataherald/dataherald#475]
Hi Team, I can create the MSSQL DB connection, sync all of the tables, and created the prompt.
**1. Prompt creation response:** 
```
[
  {
    "id": "6627a8f877f6a6414e4dff59",
    "metadata": {},
    "created_at": "2024-04-23T12:26:32.940000+00:00",
    "text": "What are top 5 selling products?",
    "db_connection_id": "6627a45577f6a6414e4dff4f"
  }
]

```

**2.** While hitting **http://localhost/api/v1/prompts/6627a8f877f6a6414e4dff59/sql-generations** using following request body:
prompt_id = 6627a8f877f6a6414e4dff59
```
{
  "finetuning_id": "string",
  "low_latency_mode": false,
  "llm_config": {
    "llm_name": "gpt-3.5-turbo",
    "api_base": "string"
  },
  "evaluate": false,
  "sql": "string",
  "metadata": {}
}
```

I am getting a response as follows:
```
response body : 
{
  "id": "6627a93077f6a6414e4dff5a",
  "metadata": {},
  "created_at": "2024-04-23T12:27:28.028396+00:00",
  "prompt_id": "6627a8f877f6a6414e4dff59",
  "finetuning_id": null,
  "status": "INVALID",
  "completed_at": "2024-04-23T12:27:29.162903+00:00",
  "llm_config": {
    "llm_name": "gpt-3.5-turbo",
    "api_base": "string"
  },
  "intermediate_steps": null,
  "sql": "string",
  "tokens_used": 0,
  "confidence_score": null,
  "error": "(pymssql._pymssql.ProgrammingError) (2812, b\"Could not find stored procedure 'string'.DB-Lib error message 20018, severity 16:\\nGeneral SQL Server error: Check messages from the SQL Server\\n\")\n\n(Background on this error at: https://sqlalche.me/e/14/f405)"
}
```
How to solve this issue?

**Comment by jcjc712** [comment]
Hi, @akshayrakate 
Did you include the `"sql": "string"` parameter in your request for sql-generation endpoint? It should only be used when you want to provide a valid SQL query that addresses the specified prompt. Therefore, the body parameter should be structured as follows:
```
{
  "low_latency_mode": false,
  "llm_config": {
    "llm_name": "gpt-3.5-turbo"
  },
  "evaluate": false,
  "metadata": {}
}
```
It is documented here https://dataherald.readthedocs.io/en/latest/api.create_sql_generation.html
```
sql: if you want to manually create the SQL query you can provide it here. If this is not provided we use the prompt to generate the SQL query.
```

Either way we will open a ticket to improve the error response, it should raise an error saying that "string" is not a valid sql.

Please let me know if you have any other question.
Regards,
