### ISSUE TITLE
Missing Apache 2.0 `LICENSE` file referenced from `README.md`

### ISSUE THREAD

**Issue by mbrukman** [Dataherald/dataherald#493]
First of all, thank you for releasing this project and sharing it with us!

The `README.md` says the license for this project is Apache 2.0 and links to a `LICENSE` file:

https://github.com/Dataherald/dataherald/blob/ab142f2e03bf8b75189c92b5f530be674d376dde/README.md?plain=1#L15-L17

However, there's no LICENSE file in the repo as of the latest commit https://github.com/Dataherald/dataherald/commit/ab142f2e03bf8b75189c92b5f530be674d376dde:

https://github.com/Dataherald/dataherald/blob/ab142f2e03bf8b75189c92b5f530be674d376dde/LICENSE returns "404 Not found"

Could you please add the license? You can find the license text here for easy copy-pasting:

* https://www.apache.org/licenses/LICENSE-2.0.txt
* https://choosealicense.com/licenses/apache-2.0/

Thanks again!

**Comment by jtimdwyer** [comment]
Looks like it was moved [here](https://github.com/Dataherald/dataherald/commit/a0a87a1c6b8ff69eff11e3461a4b71fc11b65570#diff-42f8051e0ab181f61f546fcd9fd81a4847af4cb8ea17f36bc2bb4a582b8e6108).

**Comment by mbrukman** [comment]
Fixed in https://github.com/Dataherald/dataherald/pull/494 – thanks!
